# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kiwaqt.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(23)
        self.tableWidget.setRowCount(18)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 1, item)
        self.gridLayout.addWidget(self.tableWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidget.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidget.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", " "))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "client"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "site"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "location"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "date/job ref."))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "barrier reference:"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("MainWindow", "length under test:"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "bedding load (kn/m)"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("MainWindow", "proof load (kn/m)"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("MainWindow", "bedding load(kn)"))
        item = self.tableWidget.item(2, 3)
        item.setText(_translate("MainWindow", "proofing load(kn)"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("MainWindow", "barrier/span"))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("MainWindow", "BL max deflection"))
        item = self.tableWidget.item(4, 2)
        item.setText(_translate("MainWindow", "residual deflection"))
        item = self.tableWidget.item(4, 3)
        item.setText(_translate("MainWindow", "PL)max deflection"))
        item = self.tableWidget.item(4, 4)
        item.setText(_translate("MainWindow", "residual deflection"))
        item = self.tableWidget.item(4, 5)
        item.setText(_translate("MainWindow", "recovery"))
        item = self.tableWidget.item(4, 6)
        item.setText(_translate("MainWindow", "% recovery"))
        item = self.tableWidget.item(11, 0)
        item.setText(_translate("MainWindow", "Barrier/span"))
        item = self.tableWidget.item(11, 1)
        item.setText(_translate("MainWindow", "BL) ZERO"))
        item = self.tableWidget.item(11, 2)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.item(11, 3)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.item(11, 4)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.item(11, 5)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.item(11, 6)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.item(11, 7)
        item.setText(_translate("MainWindow", "OFF"))
        item = self.tableWidget.item(11, 8)
        item.setText(_translate("MainWindow", "PL1) ZERO"))
        item = self.tableWidget.item(11, 9)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.item(11, 10)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.item(11, 11)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.item(11, 12)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.item(11, 13)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.item(11, 14)
        item.setText(_translate("MainWindow", "5MINS"))
        item = self.tableWidget.item(11, 15)
        item.setText(_translate("MainWindow", "PL2) OFF"))
        item = self.tableWidget.item(11, 16)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.item(11, 17)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.item(11, 18)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.item(11, 19)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.item(11, 20)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.item(11, 21)
        item.setText(_translate("MainWindow", "5MINS"))
        item = self.tableWidget.item(11, 22)
        item.setText(_translate("MainWindow", "OFF"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
